### ISSUE TITLE
这个项目是要付费的么？流量怎么算钱？

### ISSUE THREAD

**Issue by 1265578519** [PearInc/FogVDN#1]
还是说免费的

**Comment by liyongming1982** [comment]
播放器和下载器是开源的，但是后台边缘路由器节点是需要部署成本的。Pear这边可以低至9000-10000/Gbps(可以比较腾讯云15000的价格)

**Comment by liyongming1982** [comment]
JS SDK请参考： https://github.com/PearInc/PearDownloader.js
